### ISSUE TITLE
using conf file fails on macOS

### ISSUE THREAD

**Issue by chew-z** [jedisct1/dnscrypt-proxy#519] opened 2016-12-21 16:14 UTC
Using brew install. Launch daemon using plist with all usual parameters works without trouble but attempt to start dnscrypt-proxy with conf file and plugins results in:

```
Wed Dec 21 08:01:35 2016 [INFO] Loading plugin [/usr/local/Cellar/dnscrypt-proxy/1.8.1/lib/dnscrypt-proxy/libdcplugin_example_ldns_blocking.la]
Wed Dec 21 08:01:35 2016 [ERROR] Plugin [/usr/local/Cellar/dnscrypt-proxy/1.8.1/lib/dnscrypt-proxy/libdcplugin_example_ldns_blocking.la] can't be loaded: [No such file or directory]
Wed Dec 21 08:01:35 2016 [INFO] Loading plugin [/usr/local/Cellar/dnscrypt-proxy/1.8.1/lib/dnscrypt-proxy/libdcplugin_example_ldns_aaaa_blocking.la]
Wed Dec 21 08:01:35 2016 [ERROR] Plugin [/usr/local/Cellar/dnscrypt-proxy/1.8.1/lib/dnscrypt-proxy/libdcplugin_example_ldns_aaaa_blocking.la] can't be loaded: [No such file or directory]
Wed Dec 21 08:01:35 2016 [INFO] Loading plugin [/usr/local/Cellar/dnscrypt-proxy/1.8.1/lib/dnscrypt-proxy/libdcplugin_example_logging.la]
Wed Dec 21 08:01:35 2016 [ERROR] Plugin [/usr/local/Cellar/dnscrypt-proxy/1.8.1/lib/dnscrypt-proxy/libdcplugin_example_logging.la] can't be loaded: [No such file or directory]
Wed Dec 21 08:01:35 2016 [ERROR] Unable to load plugins
```

This is right cause I do not have *.la files but *.so files in that folder.

**Comment by jedisct1** [comment] 2016-12-21 16:17
Problem with the Homebrew formula?

The `.so` must be there...

**Comment by chew-z** [comment] 2016-12-21 16:17
Probably..

**Comment by jedisct1** [comment] 2016-12-21 16:30
Don't rename these files. `.la` and `.so` files are completely different things.

Make sure that the `ldns` package is installed, and try to reinstall the formula, maybe. `ldns` is marked as recommended, but not mandatory, and some plugins depend on it.

**Comment by chew-z** [comment] 2016-12-22 02:34
Yes, I have ldns installed via brew and dnscrypt-proxy installed with --with-plugins option. I have also tried to look into brew formula but is simply does _configure, make and install_. 

I think that not so many people on Mac use pure dnscrypt-proxy and plugins and not many of them tried so  far to make it work with conf file. However it seems that current setup won't work on Mac as it seems that brew creates .so files for plugins and you have hardcoded .la. This is just a conjecture on my side. 

It is not critical because dnscrypt-proxy works fine with my old setup (brew services and plist file with all the options) but if it helps I could remove dnscrypt-proxy completly and reinstall it with brew to confirm my guess that I am getting .so files in plugins library.

And my other suggestion is that the old way of pointing to plugin file (.so or .la) used to work well. So perhaps it could be also done in conf file optionally? Just a suggestion.

**Comment by jedisct1** [comment] 2016-12-22 07:07
I think the issue is that the Homebrew formula is missing

```
  skip_clean :la
```

/cc @ilovezfs @marcus-cr

**Comment by ilovezfs** [comment] 2016-12-22 08:18
Why are the .la files needed

**Comment by jedisct1** [comment] 2016-12-22 09:55
The `.la` files are needed in order to use the same file name to load a plugin no matter what the platform is.

**Comment by marcus-cr** [comment] 2016-12-27 23:38
@chew-z: I haven't had any issues with the `.so` plugins. I also don't use the `dnscrypt-proxy.conf` file.

If you truly want to run it 'purely' then you may want to uninstall the brewed version, compile and install dnscrypt-proxy from source, then tinker/debug so `launchd` will run it...but even then LaunchDaemons relies on `.plist` files I believe. Or just switch to Linux entirely :)

@jedisct1: Homebrew will install ldns unless `--without-ldns` is invoked. Also, the brewed version doesn't seem to leave any `.la` files left over (least I couldn't find any in `/usr/local`)

**Comment by chew-z** [comment] 2016-12-28 04:28
I do not have had any issues with brew version of dnscrypt-porxy run via brew services [launchd and plist file] and .so plugins. I couldn't run dnscrypt-proxy with .so plugins when I have tried using conf file - new functionality introduced in 1.8

In .plist for launchd or command line you can point  to .so plugins instead of .la and it works just fine on Mac. It isn't possible with conf file. That's the problem.

**Comment by jedisct1** [comment] 2016-12-28 07:17
The current dev code loads the `.so` files when using the config file.

**Closed by jedisct1** 2016-12-28 07:17 UTC

**Comment by marcus-cr** [comment] 2016-12-28 16:36
Your config file is looking for `.la` files. Perhaps a typo in your `dnscrypt-proxy.conf` file?

> Wed Dec 21 08:01:35 2016 [INFO] Loading plugin [/usr/local/Cellar/dnscrypt-proxy/1.8.1/lib/dnscrypt-proxy/libdcplugin_example_ldns_blocking.la]

**Comment by jedisct1** [comment] 2016-12-28 16:41
The config file looking for `.la` file was expected until version 1.9.0 (to be released).

`.la` files is what have been always documented, because they will work everywhere.

Starting with version 1.9.0, the config file loads `.sl/.so/.dll` files according to the platform.

**Comment by marcus-cr** [comment] 2016-12-28 18:36
I think I'm missing or overlooking something here because the config file doesn't have a plugins section. Not sure how I can help at this point since the config file in v1.9.0 will handle `.so` files.. No worries.

**Comment by felixonmars** [comment] 2016-12-29 13:30
I assume the problem arises if `BlockIPv6` was set to "yes" in the config file.

https://github.com/jedisct1/dnscrypt-proxy/blob/668c0f45cf5fa866f0c858c353cb89cbf9bb5b02/src/proxy/simpleconf_dnscrypt.h#L35

Related Arch bug: https://bugs.archlinux.org/task/52286

**Comment by jedisct1** [comment] 2016-12-29 13:58
The `LocalCache`, `Forward`, `QueryLogFile`, `BlockIPv6`, `BlackList`, `OpenDNSPasswordFile` and `OpenDNSIP` options load plugins.

**Comment by jedisct1** [comment] 2016-12-29 14:26
Now that version 1.9.0 has been released, it shouldn't be an issue any more, since plugins loaded via the configuration files use the native file names, and not the `.la` files.

**Comment by felixonmars** [comment] 2016-12-30 03:43
Thank you. All works correctly here now.
