### ISSUE TITLE
Config file on 1.9.3

### ISSUE THREAD

**Issue by zivender** [jedisct1/dnscrypt-proxy#574] opened 2017-01-20 03:31 UTC
My config file (/usr/local/etc/dnscrypt-proxy.conf) was replaced when installing v.1.9.3. I think this has been resolved on previous version ?

**Comment by jedisct1** [comment] 2017-01-20 11:47
Duplicate of https://github.com/jedisct1/dnscrypt-proxy/issues/575

**Closed by jedisct1** 2017-01-20 11:47 UTC
